### ISSUE TITLE
Question: Do you plan on supporting animation?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [yohhoy/heifreader#6]
I know the repository says it's not supported, but I don't think there is any other library that supports HEIF for Android .

Would be great if it did support animation. Do you plan on adding it?

**Comment by yohhoy** [comment]
Anwser: no.

I have no motivation (and no time) to improve this small project, because Google announced Android 9 support HEIF natively.

**Comment by AndroidDeveloperLB** [comment]
@yohhoy Too bad. 
Android 9 (P) is not available even on 0.1% of devices currently...
I was hoping to find a library that can handle it.

I hope Google will soon add support of showing this kind of content on older Android versions, because there is practically no reason to use it, if Android P is the only one that can do it.
